version: '3'

networks:
  app_net:
    driver: bridge
  nginx_net:
    driver: bridge

services:
  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx_net
  server:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "./docker/sh/server-entrypoint.sh"
    volumes:
      - ./:/app
    env_file:
      - ./tg_bot/.env
    networks:
      - nginx_net
      - app_net
    depends_on:
      - db

  scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - server
    command: /bin/sh -c "python -u manage.py scheduler"
    volumes:
      - ./:/app
    networks:
      - app_net

  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db
    restart: always
    networks:
      - app_net
    volumes:
      - ./db_data:/var/lib/postgresql/data/
