# Generated by Django 4.2.4 on 2024-12-03 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="amazonautomationtask",
            name="min_reviews_rating",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Filters search results to items with customer review ratings above specified value.",
                validators=[django.core.validators.MaxValueValidator(5)],
                verbose_name="Min Reviews Rating",
            ),
        ),
        migrations.AddField(
            model_name="amazonautomationtask",
            name="min_saving_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Filters search results to items with at least one offer having saving percentage above the specified value.",
                validators=[django.core.validators.MaxValueValidator(10)],
                verbose_name="Min Savings Percent",
            ),
        ),
    ]
