# Generated by Django 4.2.4 on 2024-11-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramBotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(max_length=150, verbose_name="Telegram Bot Name"),
                ),
                (
                    "bot_api_token",
                    models.CharField(
                        max_length=250, verbose_name="Telegram Bot API Token"
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(
                        max_length=150, verbose_name="Telegram Bot Channel Name"
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        max_length=150, verbose_name="Telegram Bot Channel ID"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Telegram Bot Enabled"
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Bot Config",
                "verbose_name_plural": "Telegram Bot Configs",
            },
        ),
    ]
