# Generated by Django 4.2.4 on 2024-11-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amazonapi",
            name="country",
        ),
    ]
