# Generated by Django 4.2.4 on 2024-11-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_telegrambotconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="AliExpressApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        max_length=250, verbose_name="AliExpress API Token"
                    ),
                ),
            ],
            options={
                "verbose_name": "AliExpress API",
                "verbose_name_plural": "AliExpress API",
            },
        ),
        migrations.CreateModel(
            name="AmazonApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        max_length=250, verbose_name="Amazon API Secret Key"
                    ),
                ),
                (
                    "access_key",
                    models.CharField(
                        max_length=250, verbose_name="Amazon API Access Key"
                    ),
                ),
                (
                    "partner_tag",
                    models.CharField(
                        max_length=250, verbose_name="Amazon API Partner Tag"
                    ),
                ),
                (
                    "country",
                    models.CharField(max_length=5, verbose_name="Amazon API Country"),
                ),
            ],
            options={
                "verbose_name": "Amazon API",
                "verbose_name_plural": "Amazon API",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Task Name")),
                (
                    "status",
                    models.CharField(
                        choices=[("New", "New"), ("Done", "Done")],
                        default="New",
                        max_length=10,
                        verbose_name="Task Status",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Start Time"),
                ),
                (
                    "api_name",
                    models.CharField(
                        choices=[("AliExpress", "AliExpress"), ("Amazon", "Amazon")],
                        max_length=15,
                        verbose_name="API Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Task",
            },
        ),
    ]
