# Generated by Django 4.2.4 on 2024-12-03 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_amazonautomationtask_min_reviews_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambotconfig",
            name="channel_link",
            field=models.CharField(
                default=" ", verbose_name="Telegram Bot Channel Link"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="amazonautomationtask",
            name="min_saving_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Filters search results to items with at least one offer having saving percentage above the specified value.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Min Savings Percent",
            ),
        ),
    ]
