# Generated by Django 4.2.4 on 2024-11-24 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_aliexpressapi_amazonapi_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Start Time"
            ),
        ),
    ]
