# Generated by Django 4.2.4 on 2024-12-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0005_remove_aliexpressapi_api_token_aliexpressapi_app_key_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aliexpressmanualtask",
            options={
                "verbose_name": "AliExpress Manual Task",
                "verbose_name_plural": "AliExpress Manual Tasks",
            },
        ),
    ]
