# Generated by Django 4.2.4 on 2024-12-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_aliexpressautomationtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="aliexpressapi",
            name="tracking_id",
            field=models.CharField(
                default=" ", max_length=300, verbose_name="AliExpress Tracking ID"
            ),
            preserve_default=False,
        ),
    ]
