# Generated by Django 4.2.4 on 2024-12-01 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_alter_amazonautomationtask_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amazonautomationtask",
            name="keywords",
            field=models.CharField(verbose_name="KeyWords"),
        ),
        migrations.AlterField(
            model_name="amazonautomationtask",
            name="num_items",
            field=models.IntegerField(
                default=1,
                help_text="Min: 1, Max: 10",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Number of Items",
            ),
        ),
    ]
