# Generated by Django 4.2.4 on 2024-12-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_aliexpressapi_tracking_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramTestBotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(
                        max_length=150, verbose_name="Telegram Test Bot Name"
                    ),
                ),
                (
                    "bot_api_token",
                    models.CharField(
                        max_length=250, verbose_name="Telegram Test Bot API Token"
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(
                        max_length=150, verbose_name="Telegram Test Bot Channel Name"
                    ),
                ),
                (
                    "channel_link",
                    models.CharField(verbose_name="Telegram Test Bot Channel Link"),
                ),
                (
                    "channel_id",
                    models.CharField(
                        max_length=150, verbose_name="Telegram Test Bot Channel ID"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Telegram Test Bot Enabled"
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Test Bot Config",
                "verbose_name_plural": "Telegram Test Bot Configs",
            },
        ),
        migrations.AlterField(
            model_name="aliexpressautomationtask",
            name="status",
            field=models.CharField(
                choices=[("New", "New"), ("Approved", "Approved"), ("Done", "Done")],
                default="New",
                max_length=10,
                verbose_name="Task Status",
            ),
        ),
        migrations.AlterField(
            model_name="aliexpressmanualtask",
            name="status",
            field=models.CharField(
                choices=[("New", "New"), ("Approved", "Approved"), ("Done", "Done")],
                default="New",
                max_length=10,
                verbose_name="Task Status",
            ),
        ),
        migrations.AlterField(
            model_name="amazonautomationtask",
            name="status",
            field=models.CharField(
                choices=[("New", "New"), ("Approved", "Approved"), ("Done", "Done")],
                default="New",
                max_length=10,
                verbose_name="Task Status",
            ),
        ),
        migrations.AlterField(
            model_name="amazonmanualtask",
            name="status",
            field=models.CharField(
                choices=[("New", "New"), ("Approved", "Approved"), ("Done", "Done")],
                default="New",
                max_length=10,
                verbose_name="Task Status",
            ),
        ),
    ]
