# Generated by Django 4.2.4 on 2024-12-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_telegramtestbotconfig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmazonSavedProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField()),
                ("image_path", models.CharField()),
                ("product_link", models.CharField()),
                ("title", models.CharField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_products",
                        to="main_app.amazonautomationtask",
                    ),
                ),
            ],
        ),
    ]
