# Generated by Django 4.2.4 on 2024-12-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_aliexpressautomationtask_min_reviews_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aliexpressautomationtask",
            name="delivery_days",
        ),
    ]
